default:
  # API server config
  tox21enricher:
    ### Database information for connecting to Postgres database ###
    driver: 'Postgres'
    server: '127.0.0.1:5432/tox21enricher'
    host: 'localhost'
    uid: 'username'
    pwd: "password"
    port: 5432
    database: 'tox21enricher'
    ### Version of application ###
    appversion: "1.0"
    ### Directories/pathing ###
    # The application's home directory
    appdir: "/home/username/tox21enricher/"
    # Location of your Python installation
    python: "/home/username/anaconda3/envs/my-rdkit-env/bin/python3.X"
    # Number of cores for multithreading
    cores: 4
  tox21enricher-queue:
    ### Database information for connecting to Postgres database ###
    driver: 'Postgres'
    server: '127.0.0.1:5432/tox21queue'
    host: 'localhost'
    uid: 'username_queue'
    pwd: "password_queue"
    port: 5432
    database: 'tox21queue'
    cleanupTime: 24
