default:
  # API server config
  tox21enricher:
    ### Database information for connecting to Postgres database ###
    driver: 'Postgres'
    server: '127.0.0.1:5432/tox21enricher'
    host: 'localhost'
    uid: 'username'
    pwd: "password"
    port: 5432
    database: 'tox21enricher'
    ### Version of application ###
    appversion: "1.0"
    ### Directories/pathing ###
    # The application's home directory
    appdir: "/home/username/tox21enricher/"
    # The application's input/output directories
    indir: "Input/"
    outdir: "Output/"
    # Location of the application's archive directory where it will save records of old requests
    archivedir: "Archive/"
    # Location of your Python installation
    python: "/home/username/anaconda3/envs/my-rdkit-env/bin/python3.X"
    # Number of cores for multithreading
    cores: 1
    # Host/port/protocol of Plumber API: used for error handling.
    apiHost: "localhost"
    apiPort: 9000
    apiSecure: false
  tox21enricher-queue:
    ### Database information for connecting to Postgres database ###
    driver: 'Postgres'
    server: '127.0.0.1:5432/tox21queue'
    host: 'localhost'
    uid: 'username_queue'
    pwd: "password_queue"
    port: 5432
    database: 'tox21queue'
    # The number of HOURS:
    #   - a transaction will be kept alive in the queue before being marked for deletion.
    #   - until the expiration of the cookie on the client storing the previous request's uuid.
    cleanupTime: 48
    # Number of DAYS before the records of an old transaction should be deleted from the database and filesystem
    deleteTime: 30
    # The maximum number of input sets that may be processed at the same time for a single request
    # NOTE: Do not set this larger than 16! Only 16 colors may be generated at a time for right now, and having this many enrichment
    #       sets can make things very slow. If this is set to be larger than 16, the app will just set it to 16.
    inputMax: 16
    # The value that determines how significant an annotation's p-value must be to be included in result files. Default of 0.2 if not set or set to an invalid value.
    pvaluedisplay: 0.2
    # Your API key needed to access the ipstack API to fetch user geolocation data: https://ipstack.com
    apikey: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxx'
