# docker-compose file for the Tox21 Enricher server-side code
# (***) denotes something that needs to be configured!

version: '2'
services:

  # Un-comment lines 9 - 19 to enable load balancing via HAProxy
  # Load balancer
  #lb:
  #  image: dockercloud/haproxy:1.2.1
  #  links:
  #   - tox21enricher
  #  volumes:
  #   - /var/run/docker.sock:/var/run/docker.sock
  #  restart: always
  #  ports:
  #   - "8002:80"
  #  expose:
  #   - "80"

  # RDKit / PostgreSQL server
  db:
    image: tox21enricher/database
    restart: always
    ports:
     - "8001:5432"
    expose:
     - "5432"
    #network_mode: host

  # Tox21 Enricher Plumber API
  tox21enricher:
    image: tox21enricher/plumber
    # (***) Replace "username" and "project_root" in the paths of the three shared volumes with the correct paths to Tox21 Enricher's Input/ and Output/ directories, as well as your Andaconda installation.
    # (***) The path to the left of the colon is the host path; the path to the right of the colon is the quest path
    volumes:
     - /home/username/project_root/Input/:/home/username/project_root/Input/
     - /home/username/project_root/Output/:/home/username/project_root/Output/
     - /home/username/anaconda3/:/home/username/anaconda3/
    restart: always
    ports: # (***) If using load balancing, change the port left of the colon to a port range formatted like n-m where m = n + (num_of_instances_of_tox21enricher - 1) (i.e., 7998-8000 for 3 instances of the Tox21 Enricher API).
     - "8000:9000"
    expose:
     - "9000"
     #network_mode: host

    # Tox21 Enricher queue
    queue:
      image: tox21enricher/queue
      volumes:
       - /home/parker/tox21enricher/Input/:/home/parker/tox21enricher/Input/
       - /home/parker/tox21enricher/Output/:/home/parker/tox21enricher/Output/
       - /home/parker/anaconda3/:/home/parker/anaconda3/
      restart: always
